# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ff32652308c2fc40d97ba32bd12f8e9407702f8dee9177b178d113a1154f7a260ecd1f712fb72e086deca3d4585a5a71ed415194bf94522f470ca593835e810

test:
  secret_key_base: 04329ca88f22de2e5e6b94d5772f4daaab8b744e574cf20b2d47ddb157e5e2554dbdf981a3e446cbf43d9d48b986fa6788b6260d9b082a4c4e6f9a51b5ffd364

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
